
# Type of connection: pcap, tcp, udp, serial
connection: pcap

# Device description
# 
# for TCP: A host:port specification. eg: 192.168.3.1:9999
# for UDP: // TODO: fill this
# for Serial: A filehandle. eg: /dev/TTYUSB0
# for PCAP: Path to file relative to package. eg: test/data/nmea/capture_004.pcap
device: test/data/nmea/capture_004.pcap

# Stream type: nmea or sbf
stream: nmea

serial:
  baudrate: 115200
  rx_serial_port: USB1
  hw_flow_control: off

frame_id: gnss

datum: ETRS89

marker_to_arp:
  delta_e: 0.0
  delta_n: 0.0
  delta_u: 0.0
  
ant_type: Unknown
ant_serial_nr: Unknown

leap_seconds: 18

polling_period:
  pvt: 500
  rest: 500

reconnect_delay_s: 2

use_gnss_time: false

ntrip_settings:
  mode: off
  caster: 0
  caster_port: 0
  username: 0
  password: 0
  mountpoint: 0
  ntrip_version: v2
  send_gga: auto
  rx_has_internet: false
  rtcm_version: RTCMv2
  rx_input_corrections_tcp: 6666
  rx_input_corrections_serial: USB2

publish:
  gpgga: false
  gprmc: false
  gpgsa: false
  gpgsv: false
  pvtcartesian: false
  pvtgeodetic: true
  poscovcartesian: false
  poscovgeodetic: true
  atteuler: true
  attcoveuler: true
  gpst : false
  navsatfix: true
  gpsfix: false
  pose: false
  diagnostics: false