name: ros-ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - ROS_DISTRO: melodic
            CLANG_FORMAT_CHECK: file
            CLANG_FORMAT_VERSION: 10

          - ROS_DISTRO: melodic
            ROS_REPO: main
            CLANG_TIDY: true

          - ROS_DISTRO: melodic
            ROS_REPO: testing
            CLANG_TIDY: true

          - ROS_DISTRO: noetic
            ROS_REPO: main
            CLANG_TIDY: true

          - ROS_DISTRO: noetic
            ROS_REPO: testing
            CLANG_TIDY: true

    env:
      CCACHE_DIR: /github/home/.ccache # Directory for ccache (and how we enable ccache in industrial_ci)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # This step will fetch/store the directory used by ccache before/after the ci run
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
